### PR TITLE
Update term to 0.5

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by Eijebong** [comment]
@Marwes Unfortunately, ascii-canvas should've been 2.0, I'd prefer @nikomatsakis to merge https://github.com/nikomatsakis/ascii-canvas/pull/3, yank 1.0.1 and publish 2.0 than merging something in lalrpop that requires 1.0.1. :(

**Comment by Marwes** [comment]
Oh, I guess this should point to ascii-canvas 2 as well https://github.com/nikomatsakis/ascii-canvas/issues/2

**Comment by Eijebong** [comment]
Yeah but it needs to be released first

**Comment by Eijebong** [comment]
There, done

**Comment by Marwes** [comment]
Great! Thanks

**Comment by CYBAI** [comment]
@Marwes @Eijebong Maybe we need a version bump for `lalrpop` so that users can have the update for `term` (and also `ascii-canvas`) by updating the version 👀? Thanks!

**Comment by Eijebong** [comment]
We do, I didn't include it here because I don't know when the last lalrpop release was and if there were any breaking changes since then?

**Comment by CYBAI** [comment]
I saw there's a minor update PR in #462 by @Marwes . I will leave my radar on it! Thanks! 😄

**Pull request merged**
