### PR TITLE
Include a pointer from the tutorial to a collection of examples

### PR DESCRIPTION
**Pull request by Pat-Lafon**
Following up on https://github.com/lalrpop/lalrpop/pull/842#discussion_r1362300955

### CODE REVIEW

**Comment by dburgener** [comment]
I'm hesitant on this.  The point of the doc content is for tutorials.  The tutorial is telling you how to use lalrpop in your own project, including Cargo.toml changes.  So to some extent, they are intended to function as examples for the users, rather than just maintaining our build system.  To that end, referencing workspaces, both complicates things for the new(er) rust user, and is likely not relevant to the user's environment.

A counter-argument could be that version and edition are not at all the salient factors here, and users will be managing their own of those independent of lalrpop.

**Comment by yannham** [comment]
After taking a second look at this, I think I agree with @dburgener. I didn't realize those were example crates from the doc, and not proper subcrates of lalrpop. Also, I guess their version has no reason to be following LALRPOP (and `nobol` was indeed `0.1.0`). Sorry for the misleading suggestion.

**Comment by dburgener** [comment]
If we do abandon the workspacification, let's grab 72c21035bd98e904282d53808b1fcd805f36ff7b by itself though.  That seems like a good change.

**Comment by youknowone** [comment]
I agree that examples under `doc` is tutorial. I think we had similar discussion couples weeks ago. Leaving a comment on doc's Cargo.toml would be helpful

**Comment by Pat-Lafon** [comment]
I guess I didn't remember the previous discussion on this. I think it still makes sense because none of these `/doc/` examples are drop in as they are. They load lalrpop via a relative path instead of via crates.io. I viewed them more as examples of grammar files(since there is a quickstart tutorial for how to set up your crate for lalrpop).

I'm not too attached to this pr though so we can just cherry-pick the second commit to raise awareness to these examples.

**Review by youknowone — APPROVED** [review]

**Pull request merged**
