### PR TITLE
Update the state index when splitting a state

### LINKED ISSUE #684: Debug assertion triggered by a simple LR(1) grammar
Reproduces with current master branch (b777a6a).

```
$ cat test.lalrpop
grammar;

extern {
    enum lexer::Tok {
        "a" => Token::A,
        "b" => Token::B,
        "c" => Token::C,
        "d" => Token::D,
        "e" => Token::E,
    }
}

pub Entry: Expr = {
    "a" <x:X> "d" => Expr::E1(x),
    "a" <y:Y> "c" => Expr::E2(y),
    "b" <y:Y> "d" => Expr::E3(y),
    "b" <x:X> "c" => Expr::E4(x),
};

X: usize = {
    "e" <x:X> => x + 1,
    "e" => 1,
};

Y: usize = {
    "e" <y:Y> => y + 1,
    "e" => 1,
};

$ ~/rust/lalrpop/target/debug/lalrpop test.lalrpop
processing file `test.lalrpop`
thread 'main' panicked at 'assertion failed: state.index.0 == index', lalrpop/src/lr1/mod.rs:54:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
   3: lalrpop::lr1::rewrite_state_indices
             at /home/omer/rust/lalrpop/lalrpop/src/lr1/mod.rs:54:9
   4: lalrpop::lr1::build_states
             at /home/omer/rust/lalrpop/lalrpop/src/lr1/mod.rs:37:5
   5: lalrpop::build::emit_recursive_ascent
             at /home/omer/rust/lalrpop/lalrpop/src/build/mod.rs:386:25
   6: lalrpop::build::process_file_into
             at /home/omer/rust/lalrpop/lalrpop/src/build/mod.rs:134:26
   7: lalrpop::build::process_file
             at /home/omer/rust/lalrpop/lalrpop/src/build/mod.rs:68:5
   8: lalrpop::api::Configuration::process_file
             at /home/omer/rust/lalrpop/lalrpop/src/api/mod.rs:244:9
   9: lalrpop::main1
             at /home/omer/rust/lalrpop/lalrpop/src/main.rs:156:15
  10: lalrpop::main
             at /home/omer/rust/lalrpop/lalrpop/src/main.rs:90:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by andersk**
Fixes #684.

### CODE REVIEW

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Changes look good but I'd like to see a regression test for #684.

**Comment by andersk** [comment]
@nikomatsakis The point of the edited test is exactly to trigger the failure in #684 without the first commit, and serve as a regression test. It’s the simplest way I know of to do that. What else do you have in mind?

```console
$ git revert e9b45821d91e4b9e8cfc8046e4ee872474b03096
[split-state-index 39c36a3] Revert "Update the state index when splitting a state"
 1 file changed, 1 insertion(+), 2 deletions(-)

$ cargo test
…
thread 'lr1::lane_table::test::paper_example_g1_build' panicked at 'assertion failed: state.index.0 == index', lalrpop/src/lr1/mod.rs:54:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    lr1::lane_table::test::paper_example_g1_build

test result: FAILED. 198 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.18s

error: test failed, to rerun pass `-p lalrpop --lib`
```

**Comment by andersk** [comment]
(Note that the grammar on which #684 was reported is the same grammar as `paper_example_g1()`, in case that’s the part that was unclear.)

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
OK, that's good

**Pull request merged**
