### PR TITLE
Allow generating no_std-compatible parsers

### LINKED ISSUE #397: Feature request: optional crate feature to generate no_std parser
I'm writing a language parser and interpreter for a `no_std` environment and I have chosen to use LALRPOP as the parser generator.  While I have made sure my grammar definition and interpreter both only use types from `core` and `alloc`, the parser generated by LALRPOP includes standard library elements (`std::vec::Vec`, `std::option::Option`, etc.)

Would it be possible to add a feature to LALRPOP where the generated parser does not use types from the standard library, thus making the parser usable in `no_std` crates?

### PR DESCRIPTION
**Pull request by coolreader18**
Fixes #397.

I went with an option rather than only using `core`/`alloc` because a) `alloc` still requires `extern crate alloc;` in the root of the crate, and b) `core` isn't available in Rust 2015, which `calculator`, `whitespace` etc are.

Oh, also, I turned off rustfmt since it was reformatting everything; I'm not sure what the formatting guidelines are for lalrpop, or if rustfmt just hasn't been run in a while.

### CODE REVIEW

**Review by Marwes — APPROVED** [review]
LGTM. 

> a) alloc still requires extern crate alloc; in the root of the crate.

Is `alloc` special in that way? Otherwise it could be declared in the generated parser's module instead.

> b) I think it core isn't available in Rust 2015, which calculator, whitespace etc are.

I think it would be fair to assume that the 2018 edition is use now (if those examples are just updated). 

So I think that perhaps the config option could be skipped if those issues are fixed?

**Comment by coolreader18** [comment]
Yep, you're right! I can put `extern crate {core,alloc};` at the top of the parser module and then the options aren't necessary.

**Review by mental32 — APPROVED** [review]
(This would be an awesome win for the embedded ecosystem)

**Comment by Marwes** [comment]
Thanks! Released as 0.19.4

**Pull request merged**
