### PR TITLE
fix visibility of internal types

### PR DESCRIPTION
**Pull request by devsnek**
Replaces #485

### CODE REVIEW

**Comment by Marwes** [comment]
Thanks!

**Comment by brendanzab** [comment]
Is this correct? I'm getting lots of errors like this, because I don't export my `Token` type publicly:

```
error[E0446]: private type `surface::Token<'source>` in public interface
   --> /target/debug/build/fathom-minimal-42e32a6ce3f9ffab/out/grammar.rs:30:18
    |
30  |         Variant0(Token<'source>),
    |                  ^^^^^^^^^^^^^^ can't leak private type
    |
   ::: experiments/rust-minimal/src/lib.rs:357:5
    |
357 |     enum Token<'source> {
    |     ------------------- `surface::Token<'source>` declared as private
```

Not sure why anything in LALRPOP should be made `pub(crate)` by default? 🤔

**Comment by brendanzab** [comment]
Is there a way that we might be able to make these underscored types private instead?

**Comment by brendanzab** [comment]
Hmm, so it seems I haven't run into this before because I've nested my token type in a private `lexer` module in the past:
```rs
pub mod surface {

    mod lexer {
        use logos::Logos;

        #[derive(Clone, Debug, Logos)]
        enum Token<'source> {
            ...
        }
    }
    
    lalrpop_mod!(grammar);
}
```
Which might be side-stepping Rust's visibility error due to a bug in rustc. But it seems like a bit of ticking time-bomb!

**Comment by Marwes** [comment]
Well they were `pub` before, so I figured `pub(crate)` was a step in the right direction :( . They should really be private, however I think that would require some refactoring as lalrpop generates a couple of inline modules which end up needing access to each others types a bit so they needed to be exported.

**Comment by brendanzab** [comment]
Ahh gotcha! Sorry for misunderstanding! Yeah making them private would be super nice - but yeah, I can see how it would be a more finicky change to make.

**Comment by oxalica** [comment]
I also get `private type [...] in public interface`. It's a common case to put the parser and lexer in private mods, and only expose some necessary wrapping methods.
I think it's better to make the visibility configurable in `lalrpop::Configuration`.

**Pull request merged**
