### PR TITLE
Update to 2018 edition

### PR DESCRIPTION
**Pull request by blakehawkins**
Hello hello

I've hit https://github.com/lalrpop/lalrpop/issues/616 with a toy project of mine and wasn't able to easily use any workarounds.

I came across https://github.com/lalrpop/lalrpop/issues/515 and done my best to implement a first step -- using 2018 across the whole repo.

Assuming all looks good here I intend to implement next steps for 2021 as well.

(I've followed https://github.com/lalrpop/lalrpop/blob/master/CONTRIBUTING.md but apologies if I missed something)

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Thanks! This seems worth doing.

**Comment by yannham** [comment]
Hi @blakehawkins, happy to merge that! However, I get the following errors when running `cargo test` on your branch:

```
error[E0432]: unresolved import `lexer`
 --> /home/yago/Dev/Rust/lalrpop-blakehawkins/target/debug/build/whitespace-f940a241e3483f6e/out/parser.rs:3:5
  |
3 | use lexer;
  |     ^^^^^ no external crate `lexer`
  |
help: consider importing one of these items instead
  |
3 | use crate::lexer;
  |     ~~~~~~~~~~~~
3 | use lalrpop_util::lexer;
  |     ~~~~~~~~~~~~~~~~~~~

error[E0432]: unresolved import `ast`
 --> /home/yago/Dev/Rust/lalrpop-blakehawkins/target/debug/build/whitespace-f940a241e3483f6e/out/parser.rs:4:5
  |
4 | use ast;
  |     ^^^ no external crate `ast`
  |
help: consider importing this module instead
  |
4 | use crate::ast;
  |     ~~~~~~~~~~

error[E0432]: unresolved import `lexer`
  --> /home/yago/Dev/Rust/lalrpop-blakehawkins/target/debug/build/whitespace-f940a241e3483f6e/out/parser.rs:16:9
   |
16 |     use lexer;
   |         ^^^^^ no external crate `lexer`
   |
help: consider importing one of these items instead
   |
16 |     use crate::lexer;
   |         ~~~~~~~~~~~~
16 |     use crate::parser::lexer;
   |         ~~~~~~~~~~~~~~~~~~~~
16 |     use lalrpop_util::lexer;
   |         ~~~~~~~~~~~~~~~~~~~

error[E0432]: unresolved import `ast`
  --> /home/yago/Dev/Rust/lalrpop-blakehawkins/target/debug/build/whitespace-f940a241e3483f6e/out/parser.rs:17:9
   |
17 |     use ast;
   |         ^^^ no external crate `ast`
   |
help: consider importing one of these items instead
   |
17 |     use crate::ast;
   |         ~~~~~~~~~~
17 |     use crate::parser::ast;
   |         ~~~~~~~~~~~~~~~~~~
```

I suspect that although you fixed the LALRPOP source themselves, LALRPOP still auto-generate Rust code that isn't compliant with the 2018 edition. I'll have a deeper look, but if you think of a solution in-between, feel free to update here!

**Comment by yannham** [comment]
I could get rid of those using the following patch:

```diff
--- a/doc/whitespace/src/parser.lalrpop
+++ b/doc/whitespace/src/parser.lalrpop
@@ -1,5 +1,5 @@
-use lexer;
-use ast;
+use crate::lexer;
+use crate::ast;
```

**Comment by yannham** [comment]
Now the tests pass, so if you're willing to just apply this patch, I'll happily merge this.

**Comment by blakehawkins** [comment]
Thanks @yannham ! 

I've also enabled edits by maintainers, please feel free to make any further changes or equally you can let me know if you have any further cr

Best

**Review by yannham — APPROVED** [review]
Rebased on lalrpop/main and tested, LGTM.

**Pull request merged**
