### PR TITLE
Change parse_X to XParser::parse.

### PR DESCRIPTION
**Pull request by ahmedcharles**
#269 Step 2.

### CODE REVIEW

**Comment by ahmedcharles** [comment]
Should wait for #316

**Comment by nikomatsakis** [comment]
Can you rebase?

**Comment by ahmedcharles** [comment]
I rebased. I'll update the docs in another commit, if that's ok? Though, I'm really curious why the CI is passing. Testing lalrpop is weird cause the build script doesn't detect that it needs to update the `.rs` based on the `.lalrpop`. Though, CI shouldn't have that problem.

**Comment by nikomatsakis** [comment]
@ahmedcharles the CI doesn't test the text of the tutorial... not sure why it should fail?

**Comment by solson** [comment]
@ahmedcharles @nikomatsakis The tutorial is still not updated and I got pretty confused trying LALRPOP for the first time!

**Pull request merged**
