### PR TITLE
Fix the tutorial links

### PR DESCRIPTION
**Pull request by lf-**
All the page links on this page were broken: http://lalrpop.github.io/lalrpop/tutorial/index.html

It appears that this is because of a duplicate tutorial/ component, so I deleted it and it seems right now.

### CODE REVIEW

**Comment by lf-** [comment]
Alrighty. I fixed the links I found, found some more broken ones with the link checker, and committed a change to CI to add the link checker that Cargo and rust-lang/Rust use, so we catch this problem earlier in the future.

**Comment by birkenfeld** [comment]
You can maybe add deleting `doc/src/lexer_tutorial.md` to this cleanup?

**Comment by lf-** [comment]
> You can maybe add deleting `doc/src/lexer_tutorial.md` to this cleanup?

Done

**Comment by nikomatsakis** [comment]
@lf- the links have been fixed, but linkcheck could still be useful, would you be willing to rebase? Sorry for not responding to this PR for so long.

**Comment by bryantbiggs** [comment]
should be resolved with #724 now

**Comment by Pat-Lafon** [comment]
I'm closing this as resolved because #724 was merged. Thanks for the PR!

**Pull request closed without merging**
