### PR TITLE
Fix broken tutorial links

### PR DESCRIPTION
**Pull request by l4l**

### CODE REVIEW

**Comment by Marwes** [comment]
These links have been changed back an forth due to people claiming they are broken so I rather not make any further changes until someone understands why they keep changing.

**Comment by l4l** [comment]
It feels these should be markdown urls actually. Also there's a [linkcheck plugin](https://github.com/Michael-F-Bryan/mdbook-linkcheck) that may help with the issue.

**Comment by l4l** [comment]
The last commit introduces [CI job](https://github.com/l4l/lalrpop/runs/4993053860?check_suite_focus=true) for link check and fixes the rest of broken ones.

**Comment by l4l** [comment]
Anything else I could do towards PR being merged?

**Pull request merged**
